const AWS = require("aws-sdk");

exports.handler = async (event, context) => {
  // receive plant_id from event request body
  const plant_id = event.body.plant_id;

  // get user email from dynamodb
  const dynamoDb = new AWS.DynamoDB.DocumentClient();
  const dydbparams = {
    TableName: process.env.TABLE_NAME,
    KeyConditionExpression: "#plant_id = :plant_id",
    ExpressionAttributeNames: {
      "#plant_id": "plant_id",
    },
    ExpressionAttributeValues: {
      ":plant_id": plant_id,
    },
  };
  const data = await dynamoDb.query(dydbparams).promise();
  console.log(data);

  // prepare send email to user
  const ses = new AWS.SES();
  const SESparams = {
    Destination: {
      ToAddresses: [data.email],
    },
    Message: {
      Body: {
        Html: {
          Data: "Dear user, <br/> <br/> Your water tank level is low, please refill it.<br/><i>This is an autogenerated email, please do not reply. </i>  <br/> <br/> Best regards, <br/> Plantify Team",
        },
      },
      Subject: {
        Data: "Water tank level is low",
      },
    },
    Source: process.env.SES_EMAIL,
    ReplyToAddresses: ["donotreply@plantify.com"],
  };
  // send email
  var statusCode = 200;
  const sesPromise = await ses.sendEmail(SESparams).promise();
  sesPromise
    .then((data) => {
      console.log(data.MessageId);
    })
    .catch((err) => {
      console.error(err, err.stack);
      statusCode = 500;
    });
  return {
    statusCode: statusCode,
    body: JSON.stringify({
      message: "post_email_water_level_low_alert",
      data: data,
    }),
  };
};
